language: bash

env:
  global:
    - PATH="/tmp/ci-tools:$PATH"
    - NODE_ENV=test

cache:
  yarn: true
  directories:
    - /tmp/ci-tools

before_install:
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh | CACHE_DIR=/tmp/ci-tools sh -s -- node=10.15.3 yarn=1.15.2

install: yarn

script: yarn test

deploy:
  provider: npm
  email: open-source@goodeggs.com
  api_token:
    secure: "brDvSFKmaXc7uIIEgHp70wOYT01oIsxpPQFR1qUJn3ol1hmV7hSc/nHsP/LBUlobmu/gCYQPrfRwsDFLbRjIeB6QVWpxmi63b0upnOOEGHKylH3KSgghj20mJTCqmIYVyHRpq+2rsycpkpIHYzV+NY9YA6uimLv1hxXJXQcWNyM="
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
