language: bash

env:
  global:
    - PATH="/tmp/ci-tools:$PATH"
    - NODE_ENV=test

cache:
  yarn: true
  directories:
    - /tmp/ci-tools

before_install:
  # WARNING: if you upgrade to node 12, mocha quietly runs no tests but exits 0. Node 14 fails to
  # yarn install due to the use of fibrous in tests.
  - curl -sSL https://github.com/goodeggs/travis-utils/raw/master/install-ci-tools.sh | CACHE_DIR=/tmp/ci-tools sh -s -- node=10.23.1 yarn=1.9.4

install: yarn --frozen-lockfile

script: yarn test

deploy:
  provider: npm
  email: open-source@goodeggs.com
  api_token:
    secure: "ZEa/6ejuHODcl3I1swX9ZB5rgNPG0ben5FCzgxU/bxf6ilrLPb9y63vSIA2pTo2JLWWcHibOqmnoFd4gpPxAuc0AQo9lvIftn4NtQP4JNkPcy5iiE+toGmX5zWotOsYfrbkQjjhkEhS58X6DR8o9ATow6VAsqD8LoQiY9EqlTL8="
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
